export enum JobRepository {
  CYBERSECURITY = "CYBERSECURITY",
  DEVOPS = "DEVOPS",
  MANAGEMENT_AND_DELIVERY = "MANAGEMENT_AND_DELIVERY",
  SOFTWARE_ENGINEERING = "SOFTWARE_ENGINEERING",
  CLOUD = "CLOUD",
  INFRASTRUCTURE = "INFRASTRUCTURE",
  AGILITY_AND_COUNSEL = "AGILITY_AND_COUNSEL",
  MOA = "MOA",
}
